package protobuf

import (
	"encoding"
)

var generators = newInterfaceRegistry()

// InterfaceMarshaler is used to differentiate implementations of an
// interface when encoding/decoding
type InterfaceMarshaler interface {
	encoding.BinaryMarshaler
	MarshalID() [8]byte
}

// InterfaceGeneratorFunc generates an instance of the implementation
// of an interface
type InterfaceGeneratorFunc func() interface{}

// GeneratorID is the key used to map the generator functions
type GeneratorID [8]byte

type generatorRegistry struct {
	generators map[GeneratorID]InterfaceGeneratorFunc
}

func newInterfaceRegistry() *generatorRegistry {
	return &generatorRegistry{
		generators: make(map[GeneratorID]InterfaceGeneratorFunc),
	}
}

func (ir *generatorRegistry) register(g InterfaceGeneratorFunc) {
	val := g().(InterfaceMarshaler)
	key := val.MarshalID()

	ir.generators[key] = g
}

func (ir *generatorRegistry) get(key GeneratorID) InterfaceGeneratorFunc {
	g, _ := ir.generators[key]
	return g
}

func (ir *generatorRegistry) has(key GeneratorID) bool {
	_, ok := ir.generators[key]
	return ok
}

// RegisterInterface registers the generator to be used to decode
// the type generated by the function
func RegisterInterface(f InterfaceGeneratorFunc) {
	generators.register(f)
}
