name: Go Tests

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        golang: ['1.13.15', '1.25.5']

    runs-on: ${{ matrix.os }}
    env:
      DBGSYNCLOG: trace
      DBGSYNCON: true

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Go ${{ matrix.golang }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.golang }}
          check-latest: false

      - name: Run tests
        run: |
          make test
